/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.11.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include <myfourstateslabelanimated.h>
#include <mylabelalarmanimated.h>
#include <mylabelalarmphotoanimated.h>
#include <mylabelalarmphototextanimated.h>
#include <mylabelanimated.h>
#include <mylabelstateanimated.h>
#include <mylabelstatetextalarmanimated.h>
#include <mylabelstatetextanimated.h>
#include <mywidgetalarmanimated.h>
#include <plot.h>
#include <qlabel_button.h>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *l_backgrond;
    Plot *widget_graph;
    MyLabelStateTextAnimated *l_modo;
    MyLabelStateTextAlarmAnimated *l_volumen;
    MyLabelStateTextAnimated *l_ie;
    MyLabelStateTextAlarmAnimated *l_bpm;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    MyWidgetAlarmAnimated *widget_alarms;
    QVBoxLayout *verticalLayout;
    QHBoxLayout *horizontalLayout;
    QLabel *l_alarm_text;
    MyLabelStateAnimated *l_power;
    MyFourStatesLabelAnimated *l_alarma;
    MyLabelAnimated *l_menu;
    QLabel *l_fecha_hora;
    QLabel *l_ventilation_state;
    QLabel *l_source_ac_dc;
    QLabel *l_battery;
    QWidget *widget_data;
    QWidget *widget_data_primary;
    MyLabelAlarmAnimated *l_PEEP_label;
    MyLabelAlarmAnimated *l_PIP_label;
    MyLabelAlarmPhotoAnimated *l_pulso0;
    MyLabelAlarmAnimated *l_Ppla;
    QLabel *label_8;
    MyLabelAlarmAnimated *l_p_min;
    MyLabelAlarmAnimated *l_PIP;
    QLabel *l_p_max_configured;
    QLabel *label_5;
    MyLabelAlarmAnimated *l_PEEP;
    MyLabelAlarmAnimated *l_Ppla_label;
    QLabel *l_line1;
    QLabel *l_line2;
    QLabel *l_line3;
    QWidget *widget_data_secundary;
    MyLabelAlarmAnimated *l_PIP_label_secundary;
    MyLabelAlarmAnimated *l_Ppla_label_secundary;
    MyLabelAlarmAnimated *l_PEEP_label_secundary;
    MyLabelAlarmAnimated *l_Pmed_label;
    QLabel *l_line4;
    QLabel *l_line5;
    MyLabelAlarmAnimated *l_Cest_label;
    QLabel *label_12;
    MyLabelAlarmPhotoAnimated *l_sin_pulso;
    QLabel *label_14;
    QLabel *label_15;
    MyLabelAlarmAnimated *l_PIP_secundary;
    MyLabelAlarmAnimated *l_Ppla_secundary;
    MyLabelAlarmAnimated *l_PEEP_secundary;
    MyLabelAlarmAnimated *l_Pmed;
    MyLabelAlarmAnimated *l_Cest;
    QLabel *label_17;
    QLabel *l_currentData_showing;
    QWidget *widget_data_terciary;
    MyLabelAlarmPhotoAnimated *l_PIP_label_terciary;
    MyLabelAlarmAnimated *l_Ppla_label_terciary;
    MyLabelAlarmPhotoAnimated *l_PEEP_label_terciary;
    QLabel *l_line4_2;
    MyLabelAlarmPhotoAnimated *l_sin_pulso_peep_terciary;
    QLabel *label_18;
    MyLabelAlarmPhotoAnimated *l_sin_pulso_pip_terciary;
    MyLabelAlarmAnimated *l_PIP_terciary;
    MyLabelAlarmAnimated *l_Ppla_terciary;
    MyLabelAlarmAnimated *l_PEEP_terciary;
    MyLabelAlarmPhotoAnimated *l_fio2_label;
    QLabel *l_line1_6;
    MyLabelAlarmPhotoAnimated *l_p_max_porcentage_terciary;
    MyLabelAlarmAnimated *l_fio2;
    MyLabelAlarmAnimated *l_fio2_configured;
    QWidget *widget_data_terciary_capnography;
    MyLabelAlarmPhotoAnimated *l_PIP_label_terciary_capnography;
    MyLabelAlarmPhotoAnimated *l_PEEP_label_terciary_capnography;
    QLabel *l_line4_3;
    MyLabelAlarmPhotoAnimated *l_sin_pulso_peep_terciary_capnography;
    MyLabelAlarmPhotoAnimated *l_sin_pulso_pip_terciary_capnography;
    MyLabelAlarmAnimated *l_PIP_terciary_capnography;
    MyLabelAlarmAnimated *l_PEEP_terciary_capnography;
    MyLabelAlarmPhotoAnimated *l_fio2_label_capnography;
    QLabel *l_line1_7;
    MyLabelAlarmPhotoAnimated *l_p_max_porcentage_terciary_capnography;
    MyLabelAlarmAnimated *l_fio2_capnography;
    MyLabelAlarmAnimated *l_fio2_configured_capnography;
    MyLabelAlarmAnimated *l_PCO2_value;
    QLabel *l_line2_2;
    MyLabelAlarmPhotoAnimated *l_mmHg;
    MyLabelAlarmPhotoAnimated *l_PCO2_label;
    MyLabelAlarmAnimated *l_etco2_configured_capnography;
    QLabel_Button *l_background_blur;
    QLabel *l_clock_error;
    QLabel *l_cartel_inicio;
    QWidget *widget_data_out;
    QLabel *l_line1_4;
    QLabel *l_line1_3;
    QLabel *l_line1_2;
    MyLabelAlarmPhotoTextAnimated *l_alarm_icon;
    QLabel *l_max_vol;
    QLabel *l_alarm_values_4;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(801, 923);
        MainWindow->setMinimumSize(QSize(801, 481));
        MainWindow->setMaximumSize(QSize(801, 16777215));
        QFont font;
        font.setFamily(QStringLiteral("Dosis"));
        MainWindow->setFont(font);
        MainWindow->setStyleSheet(QStringLiteral(""));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        l_backgrond = new QLabel(centralWidget);
        l_backgrond->setObjectName(QStringLiteral("l_backgrond"));
        l_backgrond->setGeometry(QRect(0, 0, 802, 482));
        l_backgrond->setPixmap(QPixmap(QString::fromUtf8(":/icons/fondo.png")));
        l_backgrond->setScaledContents(true);
        widget_graph = new Plot(centralWidget);
        widget_graph->setObjectName(QStringLiteral("widget_graph"));
        widget_graph->setGeometry(QRect(60, 59, 520, 300));
        l_modo = new MyLabelStateTextAnimated(centralWidget);
        l_modo->setObjectName(QStringLiteral("l_modo"));
        l_modo->setGeometry(QRect(75, 375, 85, 90));
        l_modo->setStyleSheet(QStringLiteral("border-image: url(:/icons/menu_o.png);"));
        l_modo->setPixmap(QPixmap(QString::fromUtf8(":/icons/modo_off.png")));
        l_modo->setScaledContents(true);
        l_volumen = new MyLabelStateTextAlarmAnimated(centralWidget);
        l_volumen->setObjectName(QStringLiteral("l_volumen"));
        l_volumen->setGeometry(QRect(202, 368, 98, 103));
        l_volumen->setStyleSheet(QStringLiteral("border-image: url(:/icons/menu_o.png);"));
        l_volumen->setPixmap(QPixmap(QString::fromUtf8(":/icons/volumen_off.png")));
        l_volumen->setScaledContents(true);
        l_ie = new MyLabelStateTextAnimated(centralWidget);
        l_ie->setObjectName(QStringLiteral("l_ie"));
        l_ie->setGeometry(QRect(456, 375, 85, 90));
        l_ie->setStyleSheet(QStringLiteral("border-image: url(:/icons/menu_o.png);"));
        l_ie->setPixmap(QPixmap(QString::fromUtf8(":/icons/ie_off.png")));
        l_ie->setScaledContents(true);
        l_bpm = new MyLabelStateTextAlarmAnimated(centralWidget);
        l_bpm->setObjectName(QStringLiteral("l_bpm"));
        l_bpm->setGeometry(QRect(329, 368, 98, 103));
        l_bpm->setStyleSheet(QStringLiteral("border-image: url(:/icons/menu_o.png);"));
        l_bpm->setPixmap(QPixmap(QString::fromUtf8(":/icons/bpm_off.png")));
        l_bpm->setScaledContents(true);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(58, 64, 27, 15));
        label->setPixmap(QPixmap(QString::fromUtf8(":/icons/icono_eje_y.png")));
        label->setScaledContents(true);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(89, 342, 480, 3));
        label_2->setPixmap(QPixmap(QString::fromUtf8(":/icons/eje_horizontal.png")));
        label_2->setScaledContents(true);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(88, 69, 3, 274));
        label_3->setPixmap(QPixmap(QString::fromUtf8(":/icons/eje_vertical.png")));
        label_3->setScaledContents(true);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(550, 349, 5, 10));
        label_4->setPixmap(QPixmap(QString::fromUtf8(":/icons/t.png")));
        label_4->setScaledContents(true);
        widget_alarms = new MyWidgetAlarmAnimated(centralWidget);
        widget_alarms->setObjectName(QStringLiteral("widget_alarms"));
        widget_alarms->setGeometry(QRect(60, 0, 501, 39));
        QFont font1;
        font1.setFamily(QStringLiteral("DINPro-Bold"));
        widget_alarms->setFont(font1);
        widget_alarms->setLayoutDirection(Qt::RightToLeft);
        widget_alarms->setStyleSheet(QLatin1String("border-radius: 5px;\n"
""));
        verticalLayout = new QVBoxLayout(widget_alarms);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        horizontalLayout = new QHBoxLayout();
        horizontalLayout->setSpacing(6);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        l_alarm_text = new QLabel(widget_alarms);
        l_alarm_text->setObjectName(QStringLiteral("l_alarm_text"));
        QFont font2;
        font2.setFamily(QStringLiteral("DIN Pro"));
        font2.setPointSize(18);
        font2.setBold(true);
        font2.setItalic(false);
        font2.setWeight(75);
        l_alarm_text->setFont(font2);
        l_alarm_text->setStyleSheet(QStringLiteral(""));
        l_alarm_text->setScaledContents(true);
        l_alarm_text->setAlignment(Qt::AlignCenter);

        horizontalLayout->addWidget(l_alarm_text);


        verticalLayout->addLayout(horizontalLayout);

        l_power = new MyLabelStateAnimated(centralWidget);
        l_power->setObjectName(QStringLiteral("l_power"));
        l_power->setEnabled(true);
        l_power->setGeometry(QRect(702, 380, 80, 80));
        l_power->setStyleSheet(QStringLiteral("border-image: url(:/icons/menu_o.png);"));
        l_power->setPixmap(QPixmap(QString::fromUtf8(":/icons/power_off.png")));
        l_power->setScaledContents(true);
        l_alarma = new MyFourStatesLabelAnimated(centralWidget);
        l_alarma->setObjectName(QStringLiteral("l_alarma"));
        l_alarma->setGeometry(QRect(602, 380, 80, 80));
        l_alarma->setStyleSheet(QStringLiteral("border-image: url(:/icons/menu_o.png);"));
        l_alarma->setPixmap(QPixmap(QString::fromUtf8(":/icons/alarma_off.png")));
        l_alarma->setScaledContents(true);
        l_menu = new MyLabelAnimated(centralWidget);
        l_menu->setObjectName(QStringLiteral("l_menu"));
        l_menu->setGeometry(QRect(0, 59, 40, 408));
        l_menu->setPixmap(QPixmap(QString::fromUtf8(":/icons/menu.png")));
        l_menu->setScaledContents(true);
        l_fecha_hora = new QLabel(centralWidget);
        l_fecha_hora->setObjectName(QStringLiteral("l_fecha_hora"));
        l_fecha_hora->setGeometry(QRect(600, 5, 81, 31));
        QFont font3;
        font3.setFamily(QStringLiteral("DIN Pro Cond Bold"));
        font3.setPointSize(16);
        font3.setBold(true);
        font3.setItalic(false);
        font3.setWeight(75);
        l_fecha_hora->setFont(font3);
        l_fecha_hora->setStyleSheet(QLatin1String("color: rgb(255, 255, 255);\n"
""));
        l_fecha_hora->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_ventilation_state = new QLabel(centralWidget);
        l_ventilation_state->setObjectName(QStringLiteral("l_ventilation_state"));
        l_ventilation_state->setGeometry(QRect(690, 10, 20, 21));
        QFont font4;
        font4.setFamily(QStringLiteral("Ebrima"));
        l_ventilation_state->setFont(font4);
        l_ventilation_state->setPixmap(QPixmap(QString::fromUtf8(":/icons/icon_ventilador.png")));
        l_ventilation_state->setScaledContents(true);
        l_source_ac_dc = new QLabel(centralWidget);
        l_source_ac_dc->setObjectName(QStringLiteral("l_source_ac_dc"));
        l_source_ac_dc->setGeometry(QRect(718, 11, 20, 20));
        l_source_ac_dc->setPixmap(QPixmap(QString::fromUtf8(":/icons/icon_fuente_ac.png")));
        l_source_ac_dc->setScaledContents(true);
        l_battery = new QLabel(centralWidget);
        l_battery->setObjectName(QStringLiteral("l_battery"));
        l_battery->setGeometry(QRect(750, 10, 35, 21));
        l_battery->setPixmap(QPixmap(QString::fromUtf8(":/icons/icon_bateria.png")));
        l_battery->setScaledContents(true);
        widget_data = new QWidget(centralWidget);
        widget_data->setObjectName(QStringLiteral("widget_data"));
        widget_data->setGeometry(QRect(570, 40, 215, 331));
        widget_data_primary = new QWidget(widget_data);
        widget_data_primary->setObjectName(QStringLiteral("widget_data_primary"));
        widget_data_primary->setGeometry(QRect(0, 0, 231, 331));
        l_PEEP_label = new MyLabelAlarmAnimated(widget_data_primary);
        l_PEEP_label->setObjectName(QStringLiteral("l_PEEP_label"));
        l_PEEP_label->setGeometry(QRect(40, 230, 76, 31));
        QPalette palette;
        QBrush brush(QColor(0, 204, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PEEP_label->setPalette(palette);
        QFont font5;
        font5.setFamily(QStringLiteral("DIN Pro"));
        font5.setPointSize(23);
        font5.setBold(true);
        font5.setWeight(75);
        l_PEEP_label->setFont(font5);
        l_PEEP_label->setLayoutDirection(Qt::LeftToRight);
        l_PEEP_label->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_PEEP_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_PIP_label = new MyLabelAlarmAnimated(widget_data_primary);
        l_PIP_label->setObjectName(QStringLiteral("l_PIP_label"));
        l_PIP_label->setGeometry(QRect(40, 30, 81, 31));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PIP_label->setPalette(palette1);
        l_PIP_label->setFont(font5);
        l_PIP_label->setLayoutDirection(Qt::LeftToRight);
        l_PIP_label->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_PIP_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_pulso0 = new MyLabelAlarmPhotoAnimated(widget_data_primary);
        l_pulso0->setObjectName(QStringLiteral("l_pulso0"));
        l_pulso0->setGeometry(QRect(43, 273, 57, 40));
        l_pulso0->setPixmap(QPixmap(QString::fromUtf8(":/icons/pulso0_off.png")));
        l_pulso0->setScaledContents(true);
        l_Ppla = new MyLabelAlarmAnimated(widget_data_primary);
        l_Ppla->setObjectName(QStringLiteral("l_Ppla"));
        l_Ppla->setGeometry(QRect(32, 120, 180, 98));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_Ppla->setPalette(palette2);
        QFont font6;
        font6.setFamily(QStringLiteral("DIN Pro Cond Black"));
        font6.setPointSize(65);
        font6.setBold(true);
        font6.setWeight(75);
        l_Ppla->setFont(font6);
        l_Ppla->setLayoutDirection(Qt::LeftToRight);
        l_Ppla->setStyleSheet(QLatin1String("color: rgb(0, 204, 255);\n"
""));
        l_Ppla->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_8 = new QLabel(widget_data_primary);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(43, 195, 57, 20));
        label_8->setPixmap(QPixmap(QString::fromUtf8(":/icons/sin_pulso.png")));
        label_8->setScaledContents(true);
        l_p_min = new MyLabelAlarmAnimated(widget_data_primary);
        l_p_min->setObjectName(QStringLiteral("l_p_min"));
        l_p_min->setGeometry(QRect(75, 270, 27, 21));
        QPalette palette3;
        QBrush brush1(QColor(255, 255, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        QBrush brush2(QColor(190, 190, 190, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        l_p_min->setPalette(palette3);
        QFont font7;
        font7.setFamily(QStringLiteral("DIN Pro"));
        font7.setPointSize(18);
        font7.setBold(true);
        font7.setWeight(75);
        l_p_min->setFont(font7);
        l_p_min->setLayoutDirection(Qt::LeftToRight);
        l_p_min->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_PIP = new MyLabelAlarmAnimated(widget_data_primary);
        l_PIP->setObjectName(QStringLiteral("l_PIP"));
        l_PIP->setGeometry(QRect(32, 20, 180, 98));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PIP->setPalette(palette4);
        l_PIP->setFont(font6);
        l_PIP->setLayoutDirection(Qt::LeftToRight);
        l_PIP->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_PIP->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_p_max_configured = new QLabel(widget_data_primary);
        l_p_max_configured->setObjectName(QStringLiteral("l_p_max_configured"));
        l_p_max_configured->setGeometry(QRect(73, 68, 28, 28));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        l_p_max_configured->setPalette(palette5);
        l_p_max_configured->setFont(font7);
        l_p_max_configured->setLayoutDirection(Qt::LeftToRight);
        l_p_max_configured->setScaledContents(true);
        l_p_max_configured->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        label_5 = new QLabel(widget_data_primary);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(43, 73, 56, 41));
        label_5->setPixmap(QPixmap(QString::fromUtf8(":/icons/pulso1.png")));
        label_5->setScaledContents(true);
        l_PEEP = new MyLabelAlarmAnimated(widget_data_primary);
        l_PEEP->setObjectName(QStringLiteral("l_PEEP"));
        l_PEEP->setGeometry(QRect(32, 221, 180, 98));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PEEP->setPalette(palette6);
        l_PEEP->setFont(font6);
        l_PEEP->setLayoutDirection(Qt::LeftToRight);
        l_PEEP->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_PEEP->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_Ppla_label = new MyLabelAlarmAnimated(widget_data_primary);
        l_Ppla_label->setObjectName(QStringLiteral("l_Ppla_label"));
        l_Ppla_label->setGeometry(QRect(40, 130, 81, 31));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_Ppla_label->setPalette(palette7);
        l_Ppla_label->setFont(font5);
        l_Ppla_label->setLayoutDirection(Qt::LeftToRight);
        l_Ppla_label->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_Ppla_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_line1 = new QLabel(widget_data_primary);
        l_line1->setObjectName(QStringLiteral("l_line1"));
        l_line1->setGeometry(QRect(32, 118, 180, 3));
        l_line1->setPixmap(QPixmap(QString::fromUtf8(":/icons/linea_azul.png")));
        l_line1->setScaledContents(true);
        l_line2 = new QLabel(widget_data_primary);
        l_line2->setObjectName(QStringLiteral("l_line2"));
        l_line2->setGeometry(QRect(32, 218, 180, 3));
        l_line2->setPixmap(QPixmap(QString::fromUtf8(":/icons/linea_azul.png")));
        l_line2->setScaledContents(true);
        l_line3 = new QLabel(widget_data_primary);
        l_line3->setObjectName(QStringLiteral("l_line3"));
        l_line3->setGeometry(QRect(32, 318, 180, 3));
        l_line3->setPixmap(QPixmap(QString::fromUtf8(":/icons/linea_azul.png")));
        l_line3->setScaledContents(true);
        l_Ppla->raise();
        l_PIP->raise();
        l_PEEP->raise();
        l_Ppla_label->raise();
        l_line1->raise();
        l_line2->raise();
        l_line3->raise();
        l_PIP_label->raise();
        l_PEEP_label->raise();
        label_5->raise();
        label_8->raise();
        l_pulso0->raise();
        l_p_max_configured->raise();
        l_p_min->raise();
        widget_data_secundary = new QWidget(widget_data);
        widget_data_secundary->setObjectName(QStringLiteral("widget_data_secundary"));
        widget_data_secundary->setGeometry(QRect(0, 0, 231, 331));
        l_PIP_label_secundary = new MyLabelAlarmAnimated(widget_data_secundary);
        l_PIP_label_secundary->setObjectName(QStringLiteral("l_PIP_label_secundary"));
        l_PIP_label_secundary->setGeometry(QRect(31, 40, 91, 31));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PIP_label_secundary->setPalette(palette8);
        QFont font8;
        font8.setFamily(QStringLiteral("DIN Pro"));
        font8.setPointSize(23);
        font8.setBold(false);
        font8.setItalic(false);
        font8.setWeight(50);
        l_PIP_label_secundary->setFont(font8);
        l_PIP_label_secundary->setLayoutDirection(Qt::LeftToRight);
        l_PIP_label_secundary->setStyleSheet(QLatin1String("color: rgb(0, 204, 255);\n"
""));
        l_PIP_label_secundary->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_Ppla_label_secundary = new MyLabelAlarmAnimated(widget_data_secundary);
        l_Ppla_label_secundary->setObjectName(QStringLiteral("l_Ppla_label_secundary"));
        l_Ppla_label_secundary->setGeometry(QRect(31, 90, 71, 31));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_Ppla_label_secundary->setPalette(palette9);
        QFont font9;
        font9.setFamily(QStringLiteral("DIN Pro Cond Black"));
        font9.setPointSize(23);
        font9.setBold(false);
        font9.setItalic(false);
        font9.setWeight(50);
        l_Ppla_label_secundary->setFont(font9);
        l_Ppla_label_secundary->setLayoutDirection(Qt::LeftToRight);
        l_Ppla_label_secundary->setStyleSheet(QLatin1String("color: rgb(0, 204, 255);\n"
""));
        l_Ppla_label_secundary->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_PEEP_label_secundary = new MyLabelAlarmAnimated(widget_data_secundary);
        l_PEEP_label_secundary->setObjectName(QStringLiteral("l_PEEP_label_secundary"));
        l_PEEP_label_secundary->setGeometry(QRect(31, 140, 91, 31));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PEEP_label_secundary->setPalette(palette10);
        l_PEEP_label_secundary->setFont(font9);
        l_PEEP_label_secundary->setLayoutDirection(Qt::LeftToRight);
        l_PEEP_label_secundary->setStyleSheet(QLatin1String("color: rgb(0, 204, 255);\n"
""));
        l_PEEP_label_secundary->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_Pmed_label = new MyLabelAlarmAnimated(widget_data_secundary);
        l_Pmed_label->setObjectName(QStringLiteral("l_Pmed_label"));
        l_Pmed_label->setGeometry(QRect(31, 190, 91, 31));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_Pmed_label->setPalette(palette11);
        l_Pmed_label->setFont(font9);
        l_Pmed_label->setLayoutDirection(Qt::LeftToRight);
        l_Pmed_label->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_Pmed_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_line4 = new QLabel(widget_data_secundary);
        l_line4->setObjectName(QStringLiteral("l_line4"));
        l_line4->setGeometry(QRect(32, 230, 180, 3));
        l_line4->setPixmap(QPixmap(QString::fromUtf8(":/icons/linea_azul.png")));
        l_line4->setScaledContents(true);
        l_line5 = new QLabel(widget_data_secundary);
        l_line5->setObjectName(QStringLiteral("l_line5"));
        l_line5->setGeometry(QRect(32, 320, 180, 3));
        l_line5->setStyleSheet(QStringLiteral("background-color: rgb(153, 235, 255);"));
        l_line5->setScaledContents(true);
        l_Cest_label = new MyLabelAlarmAnimated(widget_data_secundary);
        l_Cest_label->setObjectName(QStringLiteral("l_Cest_label"));
        l_Cest_label->setGeometry(QRect(31, 260, 91, 31));
        QPalette palette12;
        QBrush brush3(QColor(153, 235, 255, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        l_Cest_label->setPalette(palette12);
        l_Cest_label->setFont(font9);
        l_Cest_label->setLayoutDirection(Qt::LeftToRight);
        l_Cest_label->setStyleSheet(QLatin1String("color: rgb(153, 235, 255);\n"
""));
        l_Cest_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_12 = new QLabel(widget_data_secundary);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(165, 203, 47, 16));
        label_12->setPixmap(QPixmap(QString::fromUtf8(":/icons/sin_pulso_off.png")));
        label_12->setScaledContents(true);
        l_sin_pulso = new MyLabelAlarmPhotoAnimated(widget_data_secundary);
        l_sin_pulso->setObjectName(QStringLiteral("l_sin_pulso"));
        l_sin_pulso->setGeometry(QRect(165, 153, 47, 16));
        l_sin_pulso->setPixmap(QPixmap(QString::fromUtf8(":/icons/sin_pulso_off.png")));
        l_sin_pulso->setScaledContents(true);
        label_14 = new QLabel(widget_data_secundary);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(165, 103, 47, 16));
        label_14->setPixmap(QPixmap(QString::fromUtf8(":/icons/sin_pulso_off.png")));
        label_14->setScaledContents(true);
        label_15 = new QLabel(widget_data_secundary);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(165, 53, 47, 16));
        label_15->setPixmap(QPixmap(QString::fromUtf8(":/icons/sin_pulso_off.png")));
        label_15->setScaledContents(true);
        l_PIP_secundary = new MyLabelAlarmAnimated(widget_data_secundary);
        l_PIP_secundary->setObjectName(QStringLiteral("l_PIP_secundary"));
        l_PIP_secundary->setGeometry(QRect(30, 38, 225, 35));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PIP_secundary->setPalette(palette13);
        l_PIP_secundary->setFont(font9);
        l_PIP_secundary->setLayoutDirection(Qt::LeftToRight);
        l_PIP_secundary->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_PIP_secundary->setAlignment(Qt::AlignCenter);
        l_Ppla_secundary = new MyLabelAlarmAnimated(widget_data_secundary);
        l_Ppla_secundary->setObjectName(QStringLiteral("l_Ppla_secundary"));
        l_Ppla_secundary->setGeometry(QRect(30, 88, 225, 36));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_Ppla_secundary->setPalette(palette14);
        l_Ppla_secundary->setFont(font9);
        l_Ppla_secundary->setLayoutDirection(Qt::LeftToRight);
        l_Ppla_secundary->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_Ppla_secundary->setAlignment(Qt::AlignCenter);
        l_PEEP_secundary = new MyLabelAlarmAnimated(widget_data_secundary);
        l_PEEP_secundary->setObjectName(QStringLiteral("l_PEEP_secundary"));
        l_PEEP_secundary->setGeometry(QRect(30, 138, 225, 36));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PEEP_secundary->setPalette(palette15);
        l_PEEP_secundary->setFont(font9);
        l_PEEP_secundary->setLayoutDirection(Qt::LeftToRight);
        l_PEEP_secundary->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_PEEP_secundary->setAlignment(Qt::AlignCenter);
        l_Pmed = new MyLabelAlarmAnimated(widget_data_secundary);
        l_Pmed->setObjectName(QStringLiteral("l_Pmed"));
        l_Pmed->setGeometry(QRect(30, 188, 225, 36));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush);
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_Pmed->setPalette(palette16);
        l_Pmed->setFont(font9);
        l_Pmed->setLayoutDirection(Qt::LeftToRight);
        l_Pmed->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_Pmed->setAlignment(Qt::AlignCenter);
        l_Cest = new MyLabelAlarmAnimated(widget_data_secundary);
        l_Cest->setObjectName(QStringLiteral("l_Cest"));
        l_Cest->setGeometry(QRect(30, 260, 225, 36));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush);
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_Cest->setPalette(palette17);
        l_Cest->setFont(font9);
        l_Cest->setLayoutDirection(Qt::LeftToRight);
        l_Cest->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_Cest->setAlignment(Qt::AlignCenter);
        label_17 = new QLabel(widget_data_secundary);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(165, 260, 45, 33));
        label_17->setPixmap(QPixmap(QString::fromUtf8(":/icons/cmH20_ml.png")));
        label_17->setScaledContents(true);
        l_Cest->raise();
        l_Ppla_secundary->raise();
        l_PIP_secundary->raise();
        l_Pmed->raise();
        l_PEEP_secundary->raise();
        l_PIP_label_secundary->raise();
        l_Ppla_label_secundary->raise();
        l_PEEP_label_secundary->raise();
        l_Pmed_label->raise();
        l_line4->raise();
        l_line5->raise();
        l_Cest_label->raise();
        label_12->raise();
        l_sin_pulso->raise();
        label_14->raise();
        label_15->raise();
        label_17->raise();
        l_currentData_showing = new QLabel(widget_data);
        l_currentData_showing->setObjectName(QStringLiteral("l_currentData_showing"));
        l_currentData_showing->setGeometry(QRect(109, 10, 42, 10));
        l_currentData_showing->setPixmap(QPixmap(QString::fromUtf8(":/icons/info_point_primary.png")));
        l_currentData_showing->setScaledContents(true);
        widget_data_terciary = new QWidget(widget_data);
        widget_data_terciary->setObjectName(QStringLiteral("widget_data_terciary"));
        widget_data_terciary->setGeometry(QRect(0, 0, 231, 331));
        l_PIP_label_terciary = new MyLabelAlarmPhotoAnimated(widget_data_terciary);
        l_PIP_label_terciary->setObjectName(QStringLiteral("l_PIP_label_terciary"));
        l_PIP_label_terciary->setGeometry(QRect(30, 140, 81, 31));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush);
        palette18.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PIP_label_terciary->setPalette(palette18);
        l_PIP_label_terciary->setFont(font8);
        l_PIP_label_terciary->setLayoutDirection(Qt::LeftToRight);
        l_PIP_label_terciary->setStyleSheet(QLatin1String("color: rgb(0, 204, 255);\n"
""));
        l_PIP_label_terciary->setPixmap(QPixmap(QString::fromUtf8(":/icons/PIP_label_terciary_off.png")));
        l_PIP_label_terciary->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_Ppla_label_terciary = new MyLabelAlarmAnimated(widget_data_terciary);
        l_Ppla_label_terciary->setObjectName(QStringLiteral("l_Ppla_label_terciary"));
        l_Ppla_label_terciary->setGeometry(QRect(38, 200, 71, 31));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Active, QPalette::Text, brush);
        palette19.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette19.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_Ppla_label_terciary->setPalette(palette19);
        l_Ppla_label_terciary->setFont(font9);
        l_Ppla_label_terciary->setLayoutDirection(Qt::LeftToRight);
        l_Ppla_label_terciary->setStyleSheet(QLatin1String("color: rgb(0, 204, 255);\n"
""));
        l_Ppla_label_terciary->setPixmap(QPixmap(QString::fromUtf8(":/icons/Ppla.png")));
        l_Ppla_label_terciary->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_PEEP_label_terciary = new MyLabelAlarmPhotoAnimated(widget_data_terciary);
        l_PEEP_label_terciary->setObjectName(QStringLiteral("l_PEEP_label_terciary"));
        l_PEEP_label_terciary->setGeometry(QRect(38, 268, 91, 31));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Active, QPalette::Text, brush);
        palette20.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette20.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PEEP_label_terciary->setPalette(palette20);
        l_PEEP_label_terciary->setFont(font9);
        l_PEEP_label_terciary->setLayoutDirection(Qt::LeftToRight);
        l_PEEP_label_terciary->setStyleSheet(QLatin1String("color: rgb(0, 204, 255);\n"
""));
        l_PEEP_label_terciary->setPixmap(QPixmap(QString::fromUtf8(":/icons/PEEP_label_terciary_off.png")));
        l_PEEP_label_terciary->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_line4_2 = new QLabel(widget_data_terciary);
        l_line4_2->setObjectName(QStringLiteral("l_line4_2"));
        l_line4_2->setGeometry(QRect(32, 320, 180, 3));
        l_line4_2->setPixmap(QPixmap(QString::fromUtf8(":/icons/linea_azul.png")));
        l_line4_2->setScaledContents(true);
        l_sin_pulso_peep_terciary = new MyLabelAlarmPhotoAnimated(widget_data_terciary);
        l_sin_pulso_peep_terciary->setObjectName(QStringLiteral("l_sin_pulso_peep_terciary"));
        l_sin_pulso_peep_terciary->setGeometry(QRect(63, 298, 45, 15));
        l_sin_pulso_peep_terciary->setPixmap(QPixmap(QString::fromUtf8(":/icons/sin_pulso_peep_terciary_off.png")));
        l_sin_pulso_peep_terciary->setScaledContents(true);
        label_18 = new QLabel(widget_data_terciary);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(63, 230, 45, 15));
        label_18->setPixmap(QPixmap(QString::fromUtf8(":/icons/sin_pulso_pip_terciary_off.png")));
        label_18->setScaledContents(true);
        l_sin_pulso_pip_terciary = new MyLabelAlarmPhotoAnimated(widget_data_terciary);
        l_sin_pulso_pip_terciary->setObjectName(QStringLiteral("l_sin_pulso_pip_terciary"));
        l_sin_pulso_pip_terciary->setGeometry(QRect(63, 168, 45, 15));
        l_sin_pulso_pip_terciary->setPixmap(QPixmap(QString::fromUtf8(":/icons/sin_pulso_pip_terciary_off.png")));
        l_sin_pulso_pip_terciary->setScaledContents(true);
        l_PIP_terciary = new MyLabelAlarmAnimated(widget_data_terciary);
        l_PIP_terciary->setObjectName(QStringLiteral("l_PIP_terciary"));
        l_PIP_terciary->setGeometry(QRect(30, 123, 180, 65));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Active, QPalette::Text, brush);
        palette21.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette21.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PIP_terciary->setPalette(palette21);
        QFont font10;
        font10.setFamily(QStringLiteral("DIN Pro"));
        font10.setPointSize(40);
        font10.setBold(true);
        font10.setItalic(false);
        font10.setWeight(75);
        l_PIP_terciary->setFont(font10);
        l_PIP_terciary->setLayoutDirection(Qt::LeftToRight);
        l_PIP_terciary->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_PIP_terciary->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_PIP_terciary->setMargin(5);
        l_Ppla_terciary = new MyLabelAlarmAnimated(widget_data_terciary);
        l_Ppla_terciary->setObjectName(QStringLiteral("l_Ppla_terciary"));
        l_Ppla_terciary->setGeometry(QRect(32, 190, 180, 61));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Active, QPalette::Text, brush);
        palette22.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette22.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_Ppla_terciary->setPalette(palette22);
        l_Ppla_terciary->setFont(font10);
        l_Ppla_terciary->setLayoutDirection(Qt::LeftToRight);
        l_Ppla_terciary->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_Ppla_terciary->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_Ppla_terciary->setMargin(5);
        l_PEEP_terciary = new MyLabelAlarmAnimated(widget_data_terciary);
        l_PEEP_terciary->setObjectName(QStringLiteral("l_PEEP_terciary"));
        l_PEEP_terciary->setGeometry(QRect(32, 258, 180, 65));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Active, QPalette::Text, brush);
        palette23.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette23.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PEEP_terciary->setPalette(palette23);
        l_PEEP_terciary->setFont(font10);
        l_PEEP_terciary->setLayoutDirection(Qt::LeftToRight);
        l_PEEP_terciary->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_PEEP_terciary->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_PEEP_terciary->setMargin(5);
        l_fio2_label = new MyLabelAlarmPhotoAnimated(widget_data_terciary);
        l_fio2_label->setObjectName(QStringLiteral("l_fio2_label"));
        l_fio2_label->setGeometry(QRect(38, 40, 51, 31));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette24.setBrush(QPalette::Active, QPalette::Text, brush);
        palette24.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette24.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_fio2_label->setPalette(palette24);
        l_fio2_label->setFont(font5);
        l_fio2_label->setLayoutDirection(Qt::LeftToRight);
        l_fio2_label->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_fio2_label->setPixmap(QPixmap(QString::fromUtf8(":/icons/fio2_label_off.png")));
        l_fio2_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_line1_6 = new QLabel(widget_data_terciary);
        l_line1_6->setObjectName(QStringLiteral("l_line1_6"));
        l_line1_6->setGeometry(QRect(30, 120, 180, 3));
        l_line1_6->setStyleSheet(QStringLiteral("background-color: rgb(156, 252, 129);"));
        l_line1_6->setScaledContents(true);
        l_p_max_porcentage_terciary = new MyLabelAlarmPhotoAnimated(widget_data_terciary);
        l_p_max_porcentage_terciary->setObjectName(QStringLiteral("l_p_max_porcentage_terciary"));
        l_p_max_porcentage_terciary->setGeometry(QRect(43, 90, 48, 24));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette25.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        l_p_max_porcentage_terciary->setPalette(palette25);
        l_p_max_porcentage_terciary->setFont(font7);
        l_p_max_porcentage_terciary->setLayoutDirection(Qt::LeftToRight);
        l_p_max_porcentage_terciary->setPixmap(QPixmap(QString::fromUtf8(":/icons/p_max_porcentage_terciary_off.png")));
        l_p_max_porcentage_terciary->setScaledContents(true);
        l_p_max_porcentage_terciary->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        l_fio2 = new MyLabelAlarmAnimated(widget_data_terciary);
        l_fio2->setObjectName(QStringLiteral("l_fio2"));
        l_fio2->setGeometry(QRect(30, 20, 180, 100));
        QPalette palette26;
        QBrush brush4(QColor(156, 252, 129, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette26.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette26.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette26.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette26.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette26.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette26.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        l_fio2->setPalette(palette26);
        QFont font11;
        font11.setFamily(QStringLiteral("DIN Pro Cond Black"));
        font11.setPointSize(55);
        font11.setBold(true);
        font11.setWeight(75);
        l_fio2->setFont(font11);
        l_fio2->setLayoutDirection(Qt::LeftToRight);
        l_fio2->setStyleSheet(QStringLiteral("color: rgb(156, 252, 129);"));
        l_fio2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_fio2_configured = new MyLabelAlarmAnimated(widget_data_terciary);
        l_fio2_configured->setObjectName(QStringLiteral("l_fio2_configured"));
        l_fio2_configured->setGeometry(QRect(30, 73, 33, 31));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette27.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette27.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        QBrush brush5(QColor(164, 166, 168, 96));
        brush5.setStyle(Qt::SolidPattern);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette27.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        l_fio2_configured->setPalette(palette27);
        QFont font12;
        font12.setFamily(QStringLiteral("DIN Pro"));
        font12.setPointSize(16);
        font12.setBold(true);
        font12.setWeight(75);
        l_fio2_configured->setFont(font12);
        l_fio2_configured->setStyleSheet(QStringLiteral(""));
        l_fio2_configured->setAlignment(Qt::AlignCenter);
        l_PIP_terciary->raise();
        l_Ppla_terciary->raise();
        l_PEEP_terciary->raise();
        l_fio2->raise();
        l_PIP_label_terciary->raise();
        l_Ppla_label_terciary->raise();
        l_PEEP_label_terciary->raise();
        l_line4_2->raise();
        l_sin_pulso_peep_terciary->raise();
        label_18->raise();
        l_sin_pulso_pip_terciary->raise();
        l_fio2_label->raise();
        l_line1_6->raise();
        l_fio2_configured->raise();
        l_p_max_porcentage_terciary->raise();
        widget_data_terciary_capnography = new QWidget(widget_data);
        widget_data_terciary_capnography->setObjectName(QStringLiteral("widget_data_terciary_capnography"));
        widget_data_terciary_capnography->setGeometry(QRect(0, 0, 231, 331));
        l_PIP_label_terciary_capnography = new MyLabelAlarmPhotoAnimated(widget_data_terciary_capnography);
        l_PIP_label_terciary_capnography->setObjectName(QStringLiteral("l_PIP_label_terciary_capnography"));
        l_PIP_label_terciary_capnography->setGeometry(QRect(35, 235, 61, 31));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette28.setBrush(QPalette::Active, QPalette::Text, brush);
        palette28.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette28.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette28.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette28.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette28.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PIP_label_terciary_capnography->setPalette(palette28);
        l_PIP_label_terciary_capnography->setFont(font8);
        l_PIP_label_terciary_capnography->setLayoutDirection(Qt::LeftToRight);
        l_PIP_label_terciary_capnography->setStyleSheet(QLatin1String("color: rgb(0, 204, 255);\n"
""));
        l_PIP_label_terciary_capnography->setPixmap(QPixmap(QString::fromUtf8(":/icons/PIP_label_terciary_off.png")));
        l_PIP_label_terciary_capnography->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_PEEP_label_terciary_capnography = new MyLabelAlarmPhotoAnimated(widget_data_terciary_capnography);
        l_PEEP_label_terciary_capnography->setObjectName(QStringLiteral("l_PEEP_label_terciary_capnography"));
        l_PEEP_label_terciary_capnography->setGeometry(QRect(35, 283, 61, 31));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette29.setBrush(QPalette::Active, QPalette::Text, brush);
        palette29.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette29.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette29.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette29.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette29.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette29.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette29.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PEEP_label_terciary_capnography->setPalette(palette29);
        l_PEEP_label_terciary_capnography->setFont(font9);
        l_PEEP_label_terciary_capnography->setLayoutDirection(Qt::LeftToRight);
        l_PEEP_label_terciary_capnography->setStyleSheet(QLatin1String("color: rgb(0, 204, 255);\n"
""));
        l_PEEP_label_terciary_capnography->setPixmap(QPixmap(QString::fromUtf8(":/icons/PEEP_label_terciary_off.png")));
        l_PEEP_label_terciary_capnography->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_line4_3 = new QLabel(widget_data_terciary_capnography);
        l_line4_3->setObjectName(QStringLiteral("l_line4_3"));
        l_line4_3->setGeometry(QRect(30, 320, 180, 3));
        l_line4_3->setPixmap(QPixmap(QString::fromUtf8(":/icons/linea_azul.png")));
        l_line4_3->setScaledContents(true);
        l_sin_pulso_peep_terciary_capnography = new MyLabelAlarmPhotoAnimated(widget_data_terciary_capnography);
        l_sin_pulso_peep_terciary_capnography->setObjectName(QStringLiteral("l_sin_pulso_peep_terciary_capnography"));
        l_sin_pulso_peep_terciary_capnography->setGeometry(QRect(150, 292, 45, 15));
        l_sin_pulso_peep_terciary_capnography->setPixmap(QPixmap(QString::fromUtf8(":/icons/sin_pulso_peep_terciary_off.png")));
        l_sin_pulso_peep_terciary_capnography->setScaledContents(true);
        l_sin_pulso_pip_terciary_capnography = new MyLabelAlarmPhotoAnimated(widget_data_terciary_capnography);
        l_sin_pulso_pip_terciary_capnography->setObjectName(QStringLiteral("l_sin_pulso_pip_terciary_capnography"));
        l_sin_pulso_pip_terciary_capnography->setGeometry(QRect(150, 240, 45, 15));
        l_sin_pulso_pip_terciary_capnography->setPixmap(QPixmap(QString::fromUtf8(":/icons/sin_pulso_pip_terciary_off.png")));
        l_sin_pulso_pip_terciary_capnography->setScaledContents(true);
        l_PIP_terciary_capnography = new MyLabelAlarmAnimated(widget_data_terciary_capnography);
        l_PIP_terciary_capnography->setObjectName(QStringLiteral("l_PIP_terciary_capnography"));
        l_PIP_terciary_capnography->setGeometry(QRect(30, 221, 180, 51));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette30.setBrush(QPalette::Active, QPalette::Text, brush);
        palette30.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette30.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette30.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette30.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette30.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette30.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette30.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PIP_terciary_capnography->setPalette(palette30);
        QFont font13;
        font13.setFamily(QStringLiteral("DIN Pro"));
        font13.setPointSize(23);
        font13.setBold(true);
        font13.setItalic(false);
        font13.setWeight(75);
        l_PIP_terciary_capnography->setFont(font13);
        l_PIP_terciary_capnography->setLayoutDirection(Qt::LeftToRight);
        l_PIP_terciary_capnography->setStyleSheet(QLatin1String("color: rgb(0, 204, 255);\n"
""));
        l_PIP_terciary_capnography->setAlignment(Qt::AlignCenter);
        l_PIP_terciary_capnography->setMargin(5);
        l_PEEP_terciary_capnography = new MyLabelAlarmAnimated(widget_data_terciary_capnography);
        l_PEEP_terciary_capnography->setObjectName(QStringLiteral("l_PEEP_terciary_capnography"));
        l_PEEP_terciary_capnography->setGeometry(QRect(30, 272, 180, 51));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette31.setBrush(QPalette::Active, QPalette::Text, brush);
        palette31.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette31.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette31.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette31.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette31.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette31.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette31.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PEEP_terciary_capnography->setPalette(palette31);
        l_PEEP_terciary_capnography->setFont(font13);
        l_PEEP_terciary_capnography->setLayoutDirection(Qt::LeftToRight);
        l_PEEP_terciary_capnography->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_PEEP_terciary_capnography->setAlignment(Qt::AlignCenter);
        l_PEEP_terciary_capnography->setMargin(5);
        l_fio2_label_capnography = new MyLabelAlarmPhotoAnimated(widget_data_terciary_capnography);
        l_fio2_label_capnography->setObjectName(QStringLiteral("l_fio2_label_capnography"));
        l_fio2_label_capnography->setGeometry(QRect(38, 40, 51, 31));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette32.setBrush(QPalette::Active, QPalette::Text, brush);
        palette32.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette32.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette32.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette32.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette32.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette32.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette32.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_fio2_label_capnography->setPalette(palette32);
        l_fio2_label_capnography->setFont(font5);
        l_fio2_label_capnography->setLayoutDirection(Qt::LeftToRight);
        l_fio2_label_capnography->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_fio2_label_capnography->setPixmap(QPixmap(QString::fromUtf8(":/icons/fio2_label_off.png")));
        l_fio2_label_capnography->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_line1_7 = new QLabel(widget_data_terciary_capnography);
        l_line1_7->setObjectName(QStringLiteral("l_line1_7"));
        l_line1_7->setGeometry(QRect(30, 120, 180, 3));
        l_line1_7->setStyleSheet(QStringLiteral("background-color: rgb(156, 252, 129);"));
        l_line1_7->setScaledContents(true);
        l_p_max_porcentage_terciary_capnography = new MyLabelAlarmPhotoAnimated(widget_data_terciary_capnography);
        l_p_max_porcentage_terciary_capnography->setObjectName(QStringLiteral("l_p_max_porcentage_terciary_capnography"));
        l_p_max_porcentage_terciary_capnography->setGeometry(QRect(43, 90, 48, 24));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::WindowText, brush1);
        palette33.setBrush(QPalette::Active, QPalette::Text, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::WindowText, brush1);
        palette33.setBrush(QPalette::Inactive, QPalette::Text, brush1);
        palette33.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette33.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        l_p_max_porcentage_terciary_capnography->setPalette(palette33);
        l_p_max_porcentage_terciary_capnography->setFont(font7);
        l_p_max_porcentage_terciary_capnography->setLayoutDirection(Qt::LeftToRight);
        l_p_max_porcentage_terciary_capnography->setPixmap(QPixmap(QString::fromUtf8(":/icons/p_max_porcentage_terciary_off.png")));
        l_p_max_porcentage_terciary_capnography->setScaledContents(true);
        l_p_max_porcentage_terciary_capnography->setAlignment(Qt::AlignBottom|Qt::AlignRight|Qt::AlignTrailing);
        l_fio2_capnography = new MyLabelAlarmAnimated(widget_data_terciary_capnography);
        l_fio2_capnography->setObjectName(QStringLiteral("l_fio2_capnography"));
        l_fio2_capnography->setGeometry(QRect(30, 20, 180, 100));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette34.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette34.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette34.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette34.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette34.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette34.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette34.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette34.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        l_fio2_capnography->setPalette(palette34);
        l_fio2_capnography->setFont(font11);
        l_fio2_capnography->setLayoutDirection(Qt::LeftToRight);
        l_fio2_capnography->setStyleSheet(QStringLiteral("color: rgb(156, 252, 129);"));
        l_fio2_capnography->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_fio2_configured_capnography = new MyLabelAlarmAnimated(widget_data_terciary_capnography);
        l_fio2_configured_capnography->setObjectName(QStringLiteral("l_fio2_configured_capnography"));
        l_fio2_configured_capnography->setGeometry(QRect(30, 73, 33, 31));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette35.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette35.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette35.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette35.setBrush(QPalette::Disabled, QPalette::WindowText, brush5);
        palette35.setBrush(QPalette::Disabled, QPalette::Text, brush5);
        l_fio2_configured_capnography->setPalette(palette35);
        l_fio2_configured_capnography->setFont(font12);
        l_fio2_configured_capnography->setStyleSheet(QStringLiteral(""));
        l_fio2_configured_capnography->setAlignment(Qt::AlignCenter);
        l_PCO2_value = new MyLabelAlarmAnimated(widget_data_terciary_capnography);
        l_PCO2_value->setObjectName(QStringLiteral("l_PCO2_value"));
        l_PCO2_value->setGeometry(QRect(30, 123, 180, 97));
        QPalette palette36;
        QBrush brush6(QColor(247, 227, 102, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette36.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette36.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette36.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette36.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette36.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette36.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette36.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette36.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette36.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        l_PCO2_value->setPalette(palette36);
        l_PCO2_value->setFont(font6);
        l_PCO2_value->setLayoutDirection(Qt::LeftToRight);
        l_PCO2_value->setStyleSheet(QLatin1String("color: rgb(247, 227, 102);\n"
""));
        l_PCO2_value->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        l_line2_2 = new QLabel(widget_data_terciary_capnography);
        l_line2_2->setObjectName(QStringLiteral("l_line2_2"));
        l_line2_2->setGeometry(QRect(30, 220, 180, 3));
        l_line2_2->setStyleSheet(QStringLiteral("background-color: rgb(247, 227, 102);"));
        l_line2_2->setScaledContents(true);
        l_mmHg = new MyLabelAlarmPhotoAnimated(widget_data_terciary_capnography);
        l_mmHg->setObjectName(QStringLiteral("l_mmHg"));
        l_mmHg->setGeometry(QRect(40, 190, 61, 31));
        l_mmHg->setPixmap(QPixmap(QString::fromUtf8(":/icons/mmHg.png")));
        l_mmHg->setScaledContents(false);
        l_PCO2_label = new MyLabelAlarmPhotoAnimated(widget_data_terciary_capnography);
        l_PCO2_label->setObjectName(QStringLiteral("l_PCO2_label"));
        l_PCO2_label->setGeometry(QRect(41, 135, 81, 31));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette37.setBrush(QPalette::Active, QPalette::Text, brush);
        palette37.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette37.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette37.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette37.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette37.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette37.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette37.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        l_PCO2_label->setPalette(palette37);
        l_PCO2_label->setFont(font5);
        l_PCO2_label->setLayoutDirection(Qt::LeftToRight);
        l_PCO2_label->setStyleSheet(QStringLiteral("color: rgb(0, 204, 255);"));
        l_PCO2_label->setPixmap(QPixmap(QString::fromUtf8(":/icons/PCO2.png")));
        l_PCO2_label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        l_etco2_configured_capnography = new MyLabelAlarmAnimated(widget_data_terciary_capnography);
        l_etco2_configured_capnography->setObjectName(QStringLiteral("l_etco2_configured_capnography"));
        l_etco2_configured_capnography->setGeometry(QRect(41, 165, 33, 31));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette38.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette38.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette38.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette38.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette38.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette38.setBrush(QPalette::Disabled, QPalette::WindowText, brush6);
        palette38.setBrush(QPalette::Disabled, QPalette::Text, brush6);
        palette38.setBrush(QPalette::Disabled, QPalette::ButtonText, brush6);
        l_etco2_configured_capnography->setPalette(palette38);
        l_etco2_configured_capnography->setFont(font12);
        l_etco2_configured_capnography->setStyleSheet(QStringLiteral("color: rgb(247, 227, 102);"));
        l_etco2_configured_capnography->setAlignment(Qt::AlignCenter);
        l_PIP_terciary_capnography->raise();
        l_PEEP_terciary_capnography->raise();
        l_fio2_capnography->raise();
        l_PIP_label_terciary_capnography->raise();
        l_PEEP_label_terciary_capnography->raise();
        l_line4_3->raise();
        l_sin_pulso_peep_terciary_capnography->raise();
        l_sin_pulso_pip_terciary_capnography->raise();
        l_fio2_label_capnography->raise();
        l_line1_7->raise();
        l_p_max_porcentage_terciary_capnography->raise();
        l_fio2_configured_capnography->raise();
        l_PCO2_value->raise();
        l_line2_2->raise();
        l_mmHg->raise();
        l_PCO2_label->raise();
        l_etco2_configured_capnography->raise();
        widget_data_secundary->raise();
        widget_data_primary->raise();
        l_currentData_showing->raise();
        widget_data_terciary->raise();
        widget_data_terciary_capnography->raise();
        l_background_blur = new QLabel_Button(centralWidget);
        l_background_blur->setObjectName(QStringLiteral("l_background_blur"));
        l_background_blur->setGeometry(QRect(-1, -1, 820, 500));
        l_background_blur->setPixmap(QPixmap(QString::fromUtf8(":/icons/menu_on.png")));
        l_background_blur->setScaledContents(true);
        l_clock_error = new QLabel(centralWidget);
        l_clock_error->setObjectName(QStringLiteral("l_clock_error"));
        l_clock_error->setGeometry(QRect(570, 8, 25, 25));
        l_clock_error->setFont(font4);
        l_clock_error->setPixmap(QPixmap(QString::fromUtf8(":/icons/clock_error.png")));
        l_clock_error->setScaledContents(true);
        l_cartel_inicio = new QLabel(centralWidget);
        l_cartel_inicio->setObjectName(QStringLiteral("l_cartel_inicio"));
        l_cartel_inicio->setGeometry(QRect(160, 158, 360, 120));
        l_cartel_inicio->setPixmap(QPixmap(QString::fromUtf8(":/icons/cartel_inicio_vent.png")));
        l_cartel_inicio->setScaledContents(true);
        widget_data_out = new QWidget(centralWidget);
        widget_data_out->setObjectName(QStringLiteral("widget_data_out"));
        widget_data_out->setGeometry(QRect(570, 40, 231, 331));
        l_line1_4 = new QLabel(widget_data_out);
        l_line1_4->setObjectName(QStringLiteral("l_line1_4"));
        l_line1_4->setGeometry(QRect(32, 118, 180, 3));
        l_line1_4->setStyleSheet(QStringLiteral("background-color: rgb(66, 74, 82);"));
        l_line1_4->setScaledContents(true);
        l_line1_3 = new QLabel(widget_data_out);
        l_line1_3->setObjectName(QStringLiteral("l_line1_3"));
        l_line1_3->setGeometry(QRect(32, 218, 180, 3));
        l_line1_3->setStyleSheet(QStringLiteral("background-color: rgb(66, 74, 82);"));
        l_line1_3->setScaledContents(true);
        l_line1_2 = new QLabel(widget_data_out);
        l_line1_2->setObjectName(QStringLiteral("l_line1_2"));
        l_line1_2->setGeometry(QRect(32, 318, 180, 3));
        l_line1_2->setStyleSheet(QStringLiteral("background-color: rgb(66, 74, 82);"));
        l_line1_2->setScaledContents(true);
        l_alarm_icon = new MyLabelAlarmPhotoTextAnimated(centralWidget);
        l_alarm_icon->setObjectName(QStringLiteral("l_alarm_icon"));
        l_alarm_icon->setGeometry(QRect(520, 4, 30, 30));
        l_alarm_icon->setMaximumSize(QSize(16777215, 16777215));
        QFont font14;
        font14.setFamily(QStringLiteral("DIN Pro"));
        font14.setPointSize(12);
        font14.setBold(true);
        font14.setWeight(75);
        l_alarm_icon->setFont(font14);
        l_alarm_icon->setStyleSheet(QStringLiteral(""));
        l_alarm_icon->setScaledContents(true);
        l_alarm_icon->setAlignment(Qt::AlignCenter);
        l_max_vol = new QLabel(centralWidget);
        l_max_vol->setObjectName(QStringLiteral("l_max_vol"));
        l_max_vol->setGeometry(QRect(520, 50, 51, 31));
        QFont font15;
        font15.setFamily(QStringLiteral("DIN Pro"));
        font15.setPointSize(15);
        l_max_vol->setFont(font15);
        l_max_vol->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        l_max_vol->setAlignment(Qt::AlignCenter);
        l_alarm_values_4 = new QLabel(centralWidget);
        l_alarm_values_4->setObjectName(QStringLiteral("l_alarm_values_4"));
        l_alarm_values_4->setGeometry(QRect(430, 50, 91, 31));
        l_alarm_values_4->setFont(font15);
        l_alarm_values_4->setStyleSheet(QStringLiteral("color: rgb(255, 255, 255);"));
        l_alarm_values_4->setAlignment(Qt::AlignCenter);
        MainWindow->setCentralWidget(centralWidget);
        l_background_blur->raise();
        l_backgrond->raise();
        widget_data_out->raise();
        widget_graph->raise();
        l_modo->raise();
        l_volumen->raise();
        l_ie->raise();
        l_bpm->raise();
        label->raise();
        label_2->raise();
        label_3->raise();
        label_4->raise();
        l_power->raise();
        l_alarma->raise();
        l_menu->raise();
        l_fecha_hora->raise();
        l_ventilation_state->raise();
        l_source_ac_dc->raise();
        l_battery->raise();
        widget_data->raise();
        l_clock_error->raise();
        l_cartel_inicio->raise();
        widget_alarms->raise();
        l_alarm_icon->raise();
        l_max_vol->raise();
        l_alarm_values_4->raise();
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        l_backgrond->setText(QString());
        l_modo->setText(QString());
        l_volumen->setText(QString());
        l_ie->setText(QString());
        l_bpm->setText(QString());
        label->setText(QString());
        label_2->setText(QString());
        label_3->setText(QString());
        label_4->setText(QString());
        l_alarm_text->setText(QString());
        l_power->setText(QString());
        l_alarma->setText(QString());
        l_menu->setText(QString());
        l_fecha_hora->setText(QApplication::translate("MainWindow", "12:30am", nullptr));
        l_ventilation_state->setText(QString());
        l_source_ac_dc->setText(QString());
        l_battery->setText(QString());
        l_PEEP_label->setText(QApplication::translate("MainWindow", "PEEP", nullptr));
        l_PIP_label->setText(QApplication::translate("MainWindow", "Ppico", nullptr));
        l_pulso0->setText(QString());
        l_Ppla->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_8->setText(QString());
        l_p_min->setText(QApplication::translate("MainWindow", "0", nullptr));
        l_PIP->setText(QApplication::translate("MainWindow", "0", nullptr));
        l_p_max_configured->setText(QApplication::translate("MainWindow", "30", nullptr));
        label_5->setText(QString());
        l_PEEP->setText(QApplication::translate("MainWindow", "0", nullptr));
        l_Ppla_label->setText(QApplication::translate("MainWindow", "Ppla", nullptr));
        l_line1->setText(QString());
        l_line2->setText(QString());
        l_line3->setText(QString());
        l_PIP_label_secundary->setText(QApplication::translate("MainWindow", "Ppico", nullptr));
        l_Ppla_label_secundary->setText(QApplication::translate("MainWindow", "Ppla", nullptr));
        l_PEEP_label_secundary->setText(QApplication::translate("MainWindow", "PEEP", nullptr));
        l_Pmed_label->setText(QApplication::translate("MainWindow", "Pmed", nullptr));
        l_line4->setText(QString());
        l_line5->setText(QString());
        l_Cest_label->setText(QApplication::translate("MainWindow", "Cest", nullptr));
        label_12->setText(QString());
        l_sin_pulso->setText(QString());
        label_14->setText(QString());
        label_15->setText(QString());
        l_PIP_secundary->setText(QApplication::translate("MainWindow", "30", nullptr));
        l_Ppla_secundary->setText(QApplication::translate("MainWindow", "25", nullptr));
        l_PEEP_secundary->setText(QApplication::translate("MainWindow", "05", nullptr));
        l_Pmed->setText(QApplication::translate("MainWindow", "08", nullptr));
        l_Cest->setText(QApplication::translate("MainWindow", "60", nullptr));
        label_17->setText(QString());
        l_currentData_showing->setText(QString());
        l_PIP_label_terciary->setText(QString());
        l_Ppla_label_terciary->setText(QString());
        l_PEEP_label_terciary->setText(QString());
        l_line4_2->setText(QString());
        l_sin_pulso_peep_terciary->setText(QString());
        label_18->setText(QString());
        l_sin_pulso_pip_terciary->setText(QString());
        l_PIP_terciary->setText(QApplication::translate("MainWindow", "30", nullptr));
        l_Ppla_terciary->setText(QApplication::translate("MainWindow", "25", nullptr));
        l_PEEP_terciary->setText(QApplication::translate("MainWindow", "05", nullptr));
        l_fio2_label->setText(QString());
        l_line1_6->setText(QString());
        l_p_max_porcentage_terciary->setText(QString());
        l_fio2->setText(QApplication::translate("MainWindow", "100", nullptr));
        l_fio2_configured->setText(QApplication::translate("MainWindow", "45", nullptr));
        l_PIP_label_terciary_capnography->setText(QString());
        l_PEEP_label_terciary_capnography->setText(QString());
        l_line4_3->setText(QString());
        l_sin_pulso_peep_terciary_capnography->setText(QString());
        l_sin_pulso_pip_terciary_capnography->setText(QString());
        l_PIP_terciary_capnography->setText(QApplication::translate("MainWindow", "30", nullptr));
        l_PEEP_terciary_capnography->setText(QApplication::translate("MainWindow", "05", nullptr));
        l_fio2_label_capnography->setText(QString());
        l_line1_7->setText(QString());
        l_p_max_porcentage_terciary_capnography->setText(QString());
        l_fio2_capnography->setText(QApplication::translate("MainWindow", "100", nullptr));
        l_fio2_configured_capnography->setText(QApplication::translate("MainWindow", "45", nullptr));
        l_PCO2_value->setText(QApplication::translate("MainWindow", "0", nullptr));
        l_line2_2->setText(QString());
        l_mmHg->setText(QString());
        l_PCO2_label->setText(QString());
        l_etco2_configured_capnography->setText(QApplication::translate("MainWindow", "45", nullptr));
        l_background_blur->setText(QString());
        l_clock_error->setText(QString());
        l_cartel_inicio->setText(QString());
        l_line1_4->setText(QString());
        l_line1_3->setText(QString());
        l_line1_2->setText(QString());
        l_alarm_icon->setText(QString());
        l_max_vol->setText(QApplication::translate("MainWindow", "...", nullptr));
        l_alarm_values_4->setText(QApplication::translate("MainWindow", "M\303\241x Vol:", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
